// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UselessBot.Core.Database;

namespace UselessBot.Core.Migrations
{
    [DbContext(typeof(BotAppDbContext))]
    partial class BotAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("UselessBot.Core.Data.Gif", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Key");

                    b.Property<string>("Tag");

                    b.Property<ulong>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Gifs");
                });

            modelBuilder.Entity("UselessBot.Core.Data.Quote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Key");

                    b.Property<string>("Tag");

                    b.Property<ulong>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
